version: "2"

linters:
  default: standard
  enable:
    - gocritic
    - revive
    - misspell
    - unconvert
    - unparam
    - errorlint
  settings:
    errcheck:
      check-type-assertions: true
    govet:
      enable-all: true
      disable:
        - fieldalignment
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    revive:
      rules:
        - name: blank-imports
        - name: exported
        - name: unreachable-code
        - name: unused-parameter
  exclusions:
    presets:
      - std-error-handling
    rules:
      - path: '(.+)_test\.go'
        linters:
          - errcheck
      - text: 'unused-parameter'
        source: 'cobra\.Command'
